[package]
name = "chips"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitbybit = "1.1.0"
arbitrary-int = "1.2.1"
log = "0.4.17"

[dev-dependencies]
simplelog = "0.12.0"